[package]
name = "circle-plonk-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.5.0"
ark-relations = "0.5.1"
stwo-prover = { git = "https://github.com/Bitcoin-Wildlife-Sanctuary/stwo", branch = "move-mult-in-plonk" }
byteorder = "^1.5.0"
ark-serialize = "0.5.0"
ark-std = "0.5.0"
ark-circom = { git = "https://github.com/Bitcoin-Wildlife-Sanctuary/circom-compat", branch = "for-m31" }
itertools = "0.13.0"
ark-bn254 = "0.5.0"
ark-r1cs-std = "0.5.0"
tracing = "0.1.41"
serde = { version = "1.0.216", features = ["derive"] }

[dev-dependencies]
ark-algebra-test-templates = "0.5.0"
rand_chacha = "0.3.1"
ark-serialize = "0.5.0"
ark-std = "0.5.0"
test-log = { version = "0.2.16", features = ["trace"] }
